Repository DeveloperAcademy-POSTECH/2025-C4-A10, pull requests merged in 2025-07, with the labels that each got.

#2 프로젝트 기본 Setting(#1)
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
  .gitignore
  A10/A10.xcodeproj/project.pbxproj
  A10/A10.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  A10/A10/App/A10App.swift
  A10/A10/Data/DummyData.swift
  A10/A10/Model/Feedback.swift
  A10/A10/Network/FirestoreManager.swift
  A10/A10/Presentation/FeedbackList/FeedbackListView.swift
  A10/A10/Presentation/Onboarding/OnboardingView.swift
  A10/A10/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  A10/A10/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  A10/A10/Resources/Assets.xcassets/Contents.json
  A10/A10/Util/Enums/Font.swift
  A10/A10/Util/Extension/Color+Extension.swift
Labels: 🧠 chore

#5 ViewModelable 구현 및 예시 추가, Navigation 추가(#3)
  A10/A10.xcodeproj/project.pbxproj
  A10/A10/Model/Navigation/NavigaitionRouter.swift
  A10/A10/Model/Navigation/NavigationDestination.swift
  A10/A10/Presentation/FeedbackList/FeedbackListView.swift
  A10/A10/Presentation/FeedbackList/FeedbackListViewModel.swift
  A10/A10/Presentation/ViewModelable.swift
  A10/A10/Util/Extension/Color+Extension.swift
Labels: ⚒️ Feature

#34 회의한 데이터 모델링 추가(#7)
  GimiFeedback/GimiFeedback.xcodeproj/project.pbxproj
  GimiFeedback/GimiFeedback/Data/DummyData.swift
  GimiFeedback/GimiFeedback/Model/Feedback.swift
  GimiFeedback/GimiFeedback/Model/FeedbackCategory.swift
  GimiFeedback/GimiFeedback/Model/FeedbackContent.swift
  GimiFeedback/GimiFeedback/Model/FeedbackContentType.swift
  GimiFeedback/GimiFeedback/Network/FirestoreManager.swift
  GimiFeedback/GimiFeedback/Util/Enums/Font.swift
Labels: ⚒️ Feature

#36 Firebase SDK import와 Firestore Manager및 구조 구현(#35)
  .gitignore
  GimiFeedback/GimiFeedback.xcodeproj/project.pbxproj
  GimiFeedback/GimiFeedback.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GimiFeedback/GimiFeedback/App/AppDelegate.swift
  GimiFeedback/GimiFeedback/App/GimiFeedbackApp.swift
  GimiFeedback/GimiFeedback/Model/Feedback.swift
  GimiFeedback/GimiFeedback/Model/FeedbackCategory.swift
  GimiFeedback/GimiFeedback/Model/FeedbackContent.swift
  GimiFeedback/GimiFeedback/Model/FeedbackContentType.swift
  GimiFeedback/GimiFeedback/Network/Firestore/CollectionType.swift
  GimiFeedback/GimiFeedback/Network/Firestore/EntityRepresentable.swift
  GimiFeedback/GimiFeedback/Network/FirestoreManager.swift
  GimiFeedback/GimiFeedback/Util/Extension/Encodable+Extension.swift
Labels: ⚒️ Feature

#51 코드 입력 및 로그인 화면 이동 구현(#15)
  GimiFeedback/GimiFeedback.xcodeproj/project.pbxproj
  GimiFeedback/GimiFeedback/App/GimiFeedbackApp.swift
  GimiFeedback/GimiFeedback/Model/Navigation/NavigaitionRouter.swift
  GimiFeedback/GimiFeedback/Model/Navigation/NavigationDestination.swift
  GimiFeedback/GimiFeedback/Model/Navigation/NavigationRouter.swift
  GimiFeedback/GimiFeedback/Presentation/InputCode/InputCodeView.swift
  GimiFeedback/GimiFeedback/Presentation/Onboarding/OnboardingLoginView.swift
  GimiFeedback/GimiFeedback/Presentation/Onboarding/OnboardingStartView.swift
  GimiFeedback/GimiFeedback/Presentation/Onboarding/OnboardingView.swift
Labels: ⚒️ Feature

#52 피드백 채널 리스트 View(홈) 구현 (#38)
  GimiFeedback/.swiftlint.yml
  GimiFeedback/GimiFeedback.xcodeproj/project.pbxproj
  GimiFeedback/GimiFeedback/Presentation/FeedbackChannel/FeedbackChannelView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackChannel/FeedbackChannelViewModel.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackList/FeedbackListView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackList/FeedbackListViewModel.swift
  GimiFeedback/GimiFeedback/Presentation/ViewModelable.swift
  GimiFeedback/GimiFeedback/Util/Extension/Date+Extension.swift
Labels: 🧠 Core

#56 프로젝트 피처 폴더 및 파일들 생성(#55)
  GimiFeedback/GimiFeedback.xcodeproj/project.pbxproj
  GimiFeedback/GimiFeedback/Presentation/ChannelDetail/ChannelDetailView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelDetail/ChannelDetailViewModel.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelEdit/ChannelEditView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelList/ChannelListView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelList/ChannelListViewModel.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackDetail/FeedbackDetailView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/FeedbackWriteView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWriteComplete/FeedbackWriteCompleteView.swift
  GimiFeedback/GimiFeedback/Util/Extension/Date+Extension.swift
Labels: ⚙️ chore

#66 Main 부분 화면 분기 처리 Router 구현 및 Navigation Setting(#60)
  GimiFeedback/GimiFeedback.xcodeproj/project.pbxproj
  GimiFeedback/GimiFeedback/App/AppDelegate.swift
  GimiFeedback/GimiFeedback/App/GimiFeedbackApp.swift
  GimiFeedback/GimiFeedback/Model/Feedback.swift
  GimiFeedback/GimiFeedback/Model/FeedbackChannel.swift
  GimiFeedback/GimiFeedback/Model/FeedbackContent.swift
  GimiFeedback/GimiFeedback/Model/Navigation/MainNavigationRoutingView.swift
  GimiFeedback/GimiFeedback/Model/Navigation/NavigationDestination.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelCraeteComplete/ChannelCraeteCompleteView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelCreate/ChannelCreateView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelDetail/ChannelDetailView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelEdit/ChannelEditView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelList/ChannelListView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelList/ChannelListViewModel.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelList/SubView/ChannelListItemView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackDetail/FeedbackDetailView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/FeedbackWriteView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWriteComplete/FeedbackWriteCompleteView.swift
  GimiFeedback/GimiFeedback/Presentation/HomeView/HomeView.swift
Labels: ⚒️ Feature

#78 피드백 코드 입력 화면 구현(#27)
  GimiFeedback/GimiFeedback.xcodeproj/project.pbxproj
  GimiFeedback/GimiFeedback/Model/Navigation/MainNavigationRoutingView.swift
  GimiFeedback/GimiFeedback/Model/Navigation/NavigationDestination.swift
  GimiFeedback/GimiFeedback/Model/Navigation/StartNavigationRoutingView.swift
  GimiFeedback/GimiFeedback/Network/FirestoreManager.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelList/ChannelListView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/FeedbackWriteView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/FeedbackWriteViewModel.swift
  GimiFeedback/GimiFeedback/Presentation/InputCode/InputCodeView.swift
  GimiFeedback/GimiFeedback/Presentation/InputCode/InputCodeViewModel.swift
Labels: ⚒️ Feature

#79 피드백 작성 화면 구현(TextFeild, Button)(#30)
  GimiFeedback/GimiFeedback.xcodeproj/project.pbxproj
  GimiFeedback/GimiFeedback/Model/FeedbackContentType.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/FeedbackWriteView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/FeedbackWriteViewModel.swift
Labels: ⚒️ Feature

#86 피드백 알림을 누르면 Feedback으로 이동(#84)
  GimiFeedback/GimiFeedback.xcodeproj/project.pbxproj
  GimiFeedback/GimiFeedback/App/AppDelegate.swift
  GimiFeedback/GimiFeedback/App/GimiFeedbackApp.swift
  GimiFeedback/GimiFeedback/Network/FCMManager.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackDetail/FeedbackDetailView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackDetail/SubView/FeedbackSectionView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/FeedbackWriteViewModel.swift
  GimiFeedback/GimiFeedback/Presentation/Main/MainView.swift
  GimiFeedback/GimiFeedback/Presentation/Main/NotificationViewModel.swift
Labels: ⚒️ Feature

#91 기능 마무리 후 Main이 꼬인 부분 해결, kakao router 화면 이동 변경(#90)
  GimiFeedback/GimiFeedback.xcodeproj/project.pbxproj
  GimiFeedback/GimiFeedback.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GimiFeedback/GimiFeedback/App/GimiFeedbackApp.swift
  GimiFeedback/GimiFeedback/Network/DeepLinkManager.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelCreate/ChannelCreateView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelCreateComplete/ChannelCreateCompleteView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelDetail/ChannelDetailView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelList/ChannelListView.swift
  GimiFeedback/GimiFeedback/Presentation/CommonViewModel/DeepLinkViewModel.swift
  GimiFeedback/GimiFeedback/Presentation/CommonViewModel/NotificationViewModel.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackDetail/FeedbackDetailView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/FeedbackWriteView.swift
  GimiFeedback/GimiFeedback/Presentation/Main/MainView.swift
  GimiFeedback/GimiFeedback/Presentation/MainView/MainView.swift
  GimiFeedback/GimiFeedback/Presentation/MainView/MainViewModel.swift
  GimiFeedback/GimiFeedback/Presentation/Start/StartView.swift
  GimiFeedback/GimiFeedback/Presentation/Start/StartViewModel.swift
Labels: 🪚 Fix

#96 공통으로 사용할 컴포넌트들 구현(#89)
  GimiFeedback/GimiFeedback.xcodeproj/project.pbxproj
  GimiFeedback/GimiFeedback/App/AppDelegate.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelCreate/ChannelCreateView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelDetail/ChannelDetailView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelEdit/ChannelEditView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelList/ChannelListView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelList/ChannelListViewModel.swift
  GimiFeedback/GimiFeedback/Presentation/Components/CustomNaviModifier.swift
  GimiFeedback/GimiFeedback/Presentation/Components/GimiButtonStyle.swift
  GimiFeedback/GimiFeedback/Presentation/Components/GimiTextEditorModifier.swift
  GimiFeedback/GimiFeedback/Presentation/Components/GimiTextFieldStyle.swift
  GimiFeedback/GimiFeedback/Presentation/Components/SpeechView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackDetail/FeedbackDetailView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/FeedbackWriteView.swift
  GimiFeedback/GimiFeedback/Util/Enums/Font+Extension.swift
Labels: ⚒️ Feature

#98 유저 로그인 Flow Hi-Fi 구현 및 닉네임 받기(#97)
  GimiFeedback/GimiFeedback.xcodeproj/project.pbxproj
  GimiFeedback/GimiFeedback/App/GimiFeedbackApp.swift
  GimiFeedback/GimiFeedback/Model/Navigation/NavigationDestination.swift
  GimiFeedback/GimiFeedback/Model/Navigation/StartNavigationRoutingView.swift
  GimiFeedback/GimiFeedback/Model/User.swift
  GimiFeedback/GimiFeedback/Network/Firestore/CollectionType.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelList/ChannelListView.swift
  GimiFeedback/GimiFeedback/Presentation/InputCode/InputCodeView.swift
  GimiFeedback/GimiFeedback/Presentation/Start/LoginView.swift
  GimiFeedback/GimiFeedback/Presentation/Start/NickNameInputView.swift
  GimiFeedback/GimiFeedback/Presentation/Start/StartView.swift
  GimiFeedback/GimiFeedback/Presentation/Start/UserViewModel.swift
  GimiFeedback/GimiFeedback/Util/Extension/UserDefaults+Extension.swift
Labels: ⚒️ Feature

#115 KPT회고를 CSS회고로 하도록 변경, 유저 닉네임을 Auth에 저장(#114)
  GimiFeedback/GimiFeedback.xcodeproj/project.pbxproj
  GimiFeedback/GimiFeedback/Model/FeedbackContentType.swift
  GimiFeedback/GimiFeedback/Network/FirebaseAuthManager.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackDetail/FeedbackDetailView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackDetail/FeedbackDetailViewModel.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackDetail/SubView/FeedbackSectionView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/FeedbackWriteView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/FeedbackWriteViewModel.swift
  GimiFeedback/GimiFeedback/Presentation/Start/NickNameInputView.swift
  GimiFeedback/GimiFeedback/Presentation/Start/UserViewModel.swift
  GimiFeedback/GimiFeedback/Util/Extension/UserDefaults+Extension.swift
Labels: ⚒️ Feature

#117 닉네임 입력 화면 구현 및 분기 처리 구현(#107)
  GimiFeedback/GimiFeedback.xcodeproj/project.pbxproj
  GimiFeedback/GimiFeedback/App/GimiFeedbackApp.swift
  GimiFeedback/GimiFeedback/Model/Navigation/MainNavigationRoutingView.swift
  GimiFeedback/GimiFeedback/Model/Navigation/NavigationDestination.swift
  GimiFeedback/GimiFeedback/Model/Navigation/StartNavigationRoutingView.swift
  GimiFeedback/GimiFeedback/Model/User.swift
  GimiFeedback/GimiFeedback/Network/FirebaseAuthManager.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/FeedbackWriteView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/FeedbackWriteViewModel.swift
  GimiFeedback/GimiFeedback/Presentation/InputNickName/InputNickNameView.swift
  GimiFeedback/GimiFeedback/Presentation/Start/NickNameInputView.swift
  GimiFeedback/GimiFeedback/Presentation/Start/StartView.swift
  GimiFeedback/GimiFeedback/Presentation/Start/UserViewModel.swift
Labels: ⚒️ Feature

#127 데이터 로직 버그 수정(#126)
  ai/converting/convert_dewy_data_to_hf_hub.ipynb
  ai/converting/convert_example_data_to_hf_hub.ipynb
  ai/converting/sentiment_label_table.json
Labels: 🤖 AI

#130 피드백 생성하기 Hi-Fi 구현(#108)
  GimiFeedback/GimiFeedback.xcodeproj/project.pbxproj
  GimiFeedback/GimiFeedback/Model/FeedbackChannel.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelCreate/ChannelCreateViewModel.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelDetail/SubViews/ChannelDetail+DescriptionView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelEdit/ChannelEditView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelEdit/ChannelEditViewModel.swift
  GimiFeedback/GimiFeedback/Presentation/Components/SplitView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/FeedbackWriteView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/FeedbackWriteViewModel.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/SubViews/FeedbackWrite+ContentView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/SubViews/FeedbackWrite+HeaderView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/SubViews/FeedbackWrite+WriteView.swift
Labels: ⚒️ Feature

#132 Merge 후 프로젝트 파일이 꼬이는 현상 수정(#131)
  GimiFeedback/GimiFeedback.xcodeproj/project.pbxproj
Labels: 🪚 Fix

#138 피드백 작성에 설명 View 구현(#109)
  GimiFeedback/GimiFeedback.xcodeproj/project.pbxproj
  GimiFeedback/GimiFeedback/Presentation/Components/TopRoundedShape.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/SubViews/FeedbackWrite+HeaderView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/SubViews/FeedbackWrite+InfoView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/SubViews/FeedbackWrite+WriteView.swift
  GimiFeedback/GimiFeedback/Resources/Assets.xcassets/Image/GuideImage/GuideImage1.imageset/Contents.json
  GimiFeedback/GimiFeedback/Resources/Assets.xcassets/Image/GuideImage/GuideImage1.imageset/GuideImage1.png
  GimiFeedback/GimiFeedback/Resources/Assets.xcassets/Image/GuideImage/GuideImage1.imageset/GuideImage1@2x.png
  GimiFeedback/GimiFeedback/Resources/Assets.xcassets/Image/GuideImage/GuideImage1.imageset/GuideImage1@3x.png
  GimiFeedback/GimiFeedback/Resources/Assets.xcassets/Image/GuideImage/GuideImage1.imageset/GuideImage2.png
  GimiFeedback/GimiFeedback/Resources/Assets.xcassets/Image/GuideImage/GuideImage1.imageset/GuideImage2@2x.png
  GimiFeedback/GimiFeedback/Resources/Assets.xcassets/Image/GuideImage/GuideImage1.imageset/GuideImage2@3x.png
  GimiFeedback/GimiFeedback/Resources/Assets.xcassets/Image/GuideImage/GuideImage2.imageset/Contents.json
  GimiFeedback/GimiFeedback/Resources/Assets.xcassets/Image/GuideImage/GuideImage2.imageset/GuideImage3.png
  GimiFeedback/GimiFeedback/Resources/Assets.xcassets/Image/GuideImage/GuideImage2.imageset/GuideImage3@2x.png
  GimiFeedback/GimiFeedback/Resources/Assets.xcassets/Image/GuideImage/GuideImage2.imageset/GuideImage3@3x.png
  GimiFeedback/GimiFeedback/Resources/Assets.xcassets/Image/GuideImage/GuideImage3.imageset/Contents.json
Labels: ⚒️ Feature

#142 피드백 작성시 로딩 화면 및 에러 처리 구현(#110)
  .gitignore
  GimiFeedback/GimiFeedback.xcodeproj/project.pbxproj
  GimiFeedback/GimiFeedback/MLModel/EncoderTokenizer.swift
  GimiFeedback/GimiFeedback/Presentation/Components/GimiTextEditorModifier.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/FeedbackWriteView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/FeedbackWriteViewModel.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/LoadingView.swift
  GimiFeedback/GimiFeedback/Util/Enums/Font+Extension.swift
Labels: ⚒️ Feature

#152 메인 화면에 유저창(닉네임 변경, 로그아웃, 탈퇴) 구현(#151)
  GimiFeedback/GimiFeedback.xcodeproj/project.pbxproj
  GimiFeedback/GimiFeedback/Model/Navigation/MainNavigationRoutingView.swift
  GimiFeedback/GimiFeedback/Model/Navigation/NavigationDestination.swift
  GimiFeedback/GimiFeedback/Network/FirebaseAuthManager.swift
  GimiFeedback/GimiFeedback/Network/KakaoAuthManager.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelCreate/SubView/TitleSectionView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelList/ChannelListView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelList/SubView/ChannelList+HeaderView.swift
  GimiFeedback/GimiFeedback/Presentation/InputNickName/InputNickNameView.swift
  GimiFeedback/GimiFeedback/Presentation/Profile/ProfileView.swift
  GimiFeedback/GimiFeedback/Presentation/Start/UserViewModel.swift
Labels: ⚒️ Feature

#160 QA 진행하면서 전체적인 세부 UI 및 처리 잡기(#158)
  GimiFeedback/GimiFeedback.xcodeproj/project.pbxproj
  GimiFeedback/GimiFeedback/App/AppDelegate.swift
  GimiFeedback/GimiFeedback/Model/Navigation/MainNavigationRoutingView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelCreate/ChannelCreateView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelCreate/SubView/ChannelCreateView+DescriptionView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelCreate/SubView/ChannelCreateView+TitleView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelCreate/SubView/DescriptionSectionView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelCreate/SubView/TitleSectionView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelCreateComplete/ChannelCreateCompleteView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelCreateComplete/ChannelCreateCompleteViewModel.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelCreateComplete/SubView/ChannelCreateComplete+ContentView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelCreateComplete/SubView/ChannelCreateComplete+ShareView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelEdit/ChannelEditView.swift
  GimiFeedback/GimiFeedback/Presentation/ChannelEdit/SubViews/ChannelEdit+TitleView.swift
  GimiFeedback/GimiFeedback/Presentation/CommonViewModel/UserViewModel.swift
  GimiFeedback/GimiFeedback/Presentation/Components/LoadingView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackDetail/SubView/FeedbackDetail+ContentView.swift
  GimiFeedback/GimiFeedback/Presentation/FeedbackWrite/FeedbackWriteViewModel.swift
  GimiFeedback/GimiFeedback/Resources/Assets.xcassets/Image/Kakao/KakaoLogin.imageset/KakaoLogin.png
  GimiFeedback/GimiFeedback/Resources/Assets.xcassets/Image/Kakao/KakaoLogin.imageset/KakaoLogin@2x.png
  GimiFeedback/GimiFeedback/Resources/Assets.xcassets/Image/Kakao/KakaoLogin.imageset/KakaoLogin@3x.png
Labels: 🪠 Refactor
